version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fx-deals-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fx_deals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fx_deals"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - fx-network

  app:
    build: .
    container_name: fx-deals-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fx_deals
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - fx-network

volumes:
  postgres_data:

networks:
  fx-network:
    driver: bridge
